development:
  adapter: postgresql
  database: commitboards_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: commitboards_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
